version: "3.7"

services:
  php-serde:
    container_name: php-serde
    build:
      dockerfile: ./.docker/php/Dockerfile
      context: .
      args:
        USER_ID: $USER_ID
    env_file: .env
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    volumes:
      - .:/var/www/html/:delegated
